irihitech/Ursa.Avalonia

demo/Ursa.Demo/Pages/TagInputDemo.axaml, demo/Ursa.Demo/ViewModels/TagInputDemoViewModel.cs, src/Ursa/Controls/TagInput/TagInput.cs
解决控件在VM绑定是造成newTags和oldTags空值以及下标越界问题
=> 修复标签输入框BUG

demo/Ursa.Demo/Models/MenuKeys.cs, demo/Ursa.Demo/Pages/EnumSelectorDemo.axaml, demo/Ursa.Demo/Pages/EnumSelectorDemo.axaml.cs, demo/Ursa.Demo/ViewModels/EnumSelectorDemoViewModel.cs, demo/Ursa.Demo/ViewModels/MainViewViewModel.cs, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, src/Ursa.Themes.Semi/Controls/EnumSelector.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa/Controls/EnumSelector/EnumSelector.cs
A Control to select enum value by assigning the enum type.
=> Enum Selector

demo/Ursa.Demo/Models/MenuKeys.cs, demo/Ursa.Demo/Pages/ButtonGroupDemo.axaml, demo/Ursa.Demo/Pages/TwoTonePathIconDemo.axaml, demo/Ursa.Demo/Pages/TwoTonePathIconDemo.axaml.cs, demo/Ursa.Demo/ViewModels/MainViewViewModel.cs, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, demo/Ursa.Demo/ViewModels/TwoTonePathIconDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/TwoTonePathIcon.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa/Controls/Icons/TwoTonePathIcon.cs
This icon support IsActive property.
=> Add TwoTone icon

demo/Ursa.Demo/Pages/DialogDemo.axaml, demo/Ursa.Demo/ViewModels/DialogDemoViewModel.cs, src/Ursa/Controls/Dialog/Dialog.cs
* DialogControl 增加 ShowCustom 方法
* 修改 Demo 增加 ShowCustom  演示
=> DialogControl 增加 ShowCustom 方法

demo/Ursa.Demo/Pages/BadgeDemo.axaml, src/Ursa.Themes.Semi/Controls/Badge.axaml, src/Ursa.Themes.Semi/Themes/Dark/Badge.axaml, src/Ursa.Themes.Semi/Themes/Light/Badge.axaml
=> Fix BadgeContentForeground

demo/Ursa.Demo/Models/MenuKeys.cs, demo/Ursa.Demo/Pages/BreadcrumbDemo.axaml, demo/Ursa.Demo/Pages/BreadcrumbDemo.axaml.cs, demo/Ursa.Demo/ViewModels/BreadcrumbDemoViewModel.cs, demo/Ursa.Demo/ViewModels/MainViewViewModel.cs, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, src/Ursa.Themes.Semi/Controls/Breadcrumb.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa.Themes.Semi/Styles/Breadcrumb.axaml, src/Ursa.Themes.Semi/Styles/_index.axaml, src/Ursa/Controls/BackTop/BackTop.cs, src/Ursa/Controls/Breadcrumb/Breadcrumb.cs, src/Ursa/Controls/Breadcrumb/BreadcrumbItem.cs
Notice: it's pretty hard to implement the auto collapse feature. This initial implementation only focus on full expanded breadcrumb.
=> Breadcrumb

demo/Ursa.Demo/Pages/NavMenuDemo.axaml, demo/Ursa.Demo/Views/MainView.axaml, src/Ursa.Themes.Semi/Controls/NavMenu.axaml, src/Ursa/Controls/NavMenu/NavMenu.cs
=> Fix: fix NavMenu layout issue. 

demo/Ursa.Demo/Pages/VerificationCodeDemo.axaml, demo/Ursa.Demo/Pages/VerificationCodeDemo.axaml.cs, demo/Ursa.Demo/ViewModels/MainViewViewModel.cs, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, demo/Ursa.Demo/ViewModels/VerificationCodeDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/VerificationCode.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa/Controls/VerificationCode/VerificationCode.cs, src/Ursa/Controls/VerificationCode/VerificationCodeCollection.cs, src/Ursa/Controls/VerificationCode/VerificationCodeCompleteEventArgs.cs, src/Ursa/Controls/VerificationCode/VerificationCodeItem.cs, src/Ursa/Controls/VerificationCode/VerificationCodeMode.cs
=> Verification code

demo/Ursa.Demo.Android/Ursa.Demo.Android.csproj, demo/Ursa.Demo.Browser/Ursa.Demo.Browser.csproj, demo/Ursa.Demo.iOS/Ursa.Demo.iOS.csproj, demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml, demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml.cs, demo/Ursa.Demo/Ursa.Demo.csproj, demo/Ursa.Demo/ViewModels/NumericUpDownDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/NumericUpDown.axaml, src/Ursa/Controls/NumericUpDown/IntUpDown.cs, src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
1. _HorizontalContentAlignment
2. new demo 
3. fix #172 
4. should not SyncTextAndValue while fromTextToValue and clamp
=> bug fix and  add new NumericUpDownDemo

demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml, src/Ursa.Themes.Semi/Controls/NumericUpDown.axaml, src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
1. simplify code for nullable control event assignment
2. make textbox readonly and dragpanel visible controlled in code behind.
3. Use compile binding in demo.
=> Read-only and Draggable fix. 

demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml, demo/Ursa.Demo/ViewModels/NumericUpDownDemoViewModel.cs, src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs, src/Ursa/Ursa.csproj
2. support bin
3. update hex input logic
4. update demo
=> 1. fix OnFormatChange

demo/Ursa.Demo/Pages/PaginationDemo.axaml, demo/Ursa.Demo/ViewModels/PaginationDemoViewModel.cs, src/Ursa/Controls/Pagination/Pagination.cs
为 Pagination 控件增加 CurrentPageChanged 事件
为 Pagination 控件增加 Command 属性
为 Pagination 控件增加 Command 属性的使用 Demo
#178
=> 为 Pagination 控件增加 CurrentPageChanged 事件

demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml, demo/Ursa.Demo/ViewModels/NumericUpDownDemoViewModel.cs, src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
command support
fix https://github.com/irihitech/Ursa.Avalonia/issues/179
=> number_updown_command

demo/Ursa.Demo/Pages/DialogDemo.axaml, demo/Ursa.Demo/ViewModels/DialogDemoViewModel.cs, demo/Ursa.Demo/ViewModels/DrawerDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/Dialog.axaml, src/Ursa.Themes.Semi/Controls/DialogShared.axaml, src/Ursa.Themes.Semi/Controls/Drawer.axaml, src/Ursa.Themes.Semi/Controls/MessageBox.axaml, src/Ursa/Controls/Dialog/DialogControlBase.cs, src/Ursa/Controls/Dialog/Options/OverlayDialogOptions.cs, src/Ursa/Controls/Dialog/OverlayDialog.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Shared.cs
Closes #134 
Closes #163 
Closes #180
=> Dialog Update

demo/Ursa.Demo/Pages/TimePickerDemo.axaml, src/Ursa.Themes.Semi/Controls/TextBox.axaml, src/Ursa.Themes.Semi/Controls/TimePicker.axaml, src/Ursa.Themes.Semi/Controls/TimeRangePicker.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa/Controls/DateTimePicker/TimePicker.cs, src/Ursa/Controls/DateTimePicker/TimePickerBase.cs, src/Ursa/Controls/DateTimePicker/TimeRangePicker.cs
And updates corresponding to TimePicker.
=> TimeRangePicker

demo/Ursa.Demo/ViewModels/SelectionListDemoViewModel.cs, src/Ursa/Controls/SelectionList/SelectionList.cs
=> Fix: ensure indicator is visibility upon loaded.

demo/Ursa.Demo/Dialogs/PlainDialog.axaml, demo/Ursa.Demo/Dialogs/PlainDialogViewModel.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs
Please help to review: @nblfeng
=> OverlayDialog: fix overlay dialog oversize display issue. 

src/Ursa/Controls/TimeBox.cs
Fix when TimeBox is contained in DataGrid, TimeBox can not be edit at all.
=> (fix) Some functionality doesn't work when TimeBox is contained in DataGrid

demo/Ursa.Demo/Pages/TimePickerDemo.axaml, src/Ursa.Themes.Semi/Controls/TimeRangePicker.axaml, src/Ursa/Controls/DateTimePicker/TimePicker.cs, src/Ursa/Controls/DateTimePicker/TimePickerPresenter.cs
Fix https://github.com/irihitech/Ursa.Avalonia/issues/235 second issue. 
Fix https://github.com/irihitech/Ursa.Avalonia/issues/230
=> TimePicker Fixes

src/Ursa.Themes.Semi/Controls/NumericUpDown.axaml
=> Fix numeric data validation error binding parent type.

demo/Ursa.Demo/Dialogs/PlainDialogViewModel.cs, demo/Ursa.Demo/Pages/DialogDemo.axaml, demo/Ursa.Demo/ViewModels/DialogDemoViewModel.cs, src/Ursa/Controls/Dialog/Dialog.cs, src/Ursa/Controls/Dialog/Options/DialogOptions.cs
Icon: inherit from owner if it is available.
ShowInTaskBar: a new optional parameter of DialogOptions.
=> Add  Icon&ShowInTaskBar for DialogWindow

demo/Ursa.Demo/Pages/TagInputDemo.axaml, src/Ursa.Themes.Semi/Controls/TagInput.axaml, src/Ursa/Controls/TagInput/TagInput.cs
=> Improve Taginput: Support MaxCount, AcceptReturn and Watermark

src/Ursa.Themes.Semi/Controls/Form.axaml
=> Hide FormGroup header related features if header is null.

demo/Ursa.Demo/Pages/ElasticWrapPanelDemo.axaml, src/Ursa.Themes.Semi/Controls/EnumSelector.axaml
=> Fix EnumSelector default Width & Alignment.

demo/Ursa.Demo.Browser/AvaloniaAppBuilderExtensions.cs, demo/Ursa.Demo.Browser/Program.cs, demo/Ursa.Demo.Browser/Roots.xml, demo/Ursa.Demo.Browser/Ursa.Demo.Browser.csproj, demo/Ursa.Demo.Browser/linker.xml
add font to Browser demo using `SourceHanSans`.
=> Browser demo font

demo/Ursa.Demo/Views/MainWindow.axaml, src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
=> Remove caption buttons on macOS

demo/Ursa.Demo/Pages/DatePickerDemo.axaml, src/Ursa.Themes.Semi/Controls/DatePicker.axaml, src/Ursa.Themes.Semi/Controls/DateRangePicker.axaml, src/Ursa/Controls/DateTimePicker/CalendarDayButton.cs, src/Ursa/Controls/DateTimePicker/DatePicker.cs, src/Ursa/Controls/DateTimePicker/DateRangePicker.cs
修复 DatePicker 和 DateRangePicker  FontSize 在文本框上未生效的问题
修复 CalendarDayButton.DatePreviewed 绑定到 DateSelectedEvent 的问题
=> 修复 DatePicker 2处问题

src/Ursa/Controls/TitleBar/TitleBar.cs
https://github.com/irihitech/Ursa.Avalonia/issues/298
=> 修复 全屏后 窗口仍可拖拽的问题

demo/Ursa.Demo/Pages/DatePickerDemo.axaml, src/Ursa.Themes.Semi/Controls/DatePicker.axaml, src/Ursa.Themes.Semi/Controls/DateRangePicker.axaml, src/Ursa/Controls/DateTimePicker/DatePicker.cs, src/Ursa/Controls/DateTimePicker/DateRangePicker.cs
=> Fix: DatePicker ClearButton and LostFocus behavior

src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Shared.cs
1. Fix modal status leak through issue.
2. Fix the issue that dialog host cannot be unregistered properly.
=> Fix Modal status issue and un-register issue

src/Ursa/Controls/EnumSelector/EnumSelector.cs
Solution:
`Enum.GetValues` does not support native aot even use `[DynamicDependency]`. but `Enum.GetValuesAsUnderlyingType` support. The difference is `Enum.GetValues` return `Enum[]` `Enum.GetValuesAsUnderlyingType` return `int[]`. Use `Enum.ToObject` can convert `int` to `Enum` and the problem is solved.
Already test on my local Windows/x86 machine.
Addition:
`netstandard2.0` does not have `Enum.GetValuesAsUnderlyingType`. So I use the `NET8_0_OR_GREATER` to make it compile.
It should not be a problem because `netstandard2.0` does not support native aot.
=> enum selector support native aot

demo/Ursa.Demo/Pages/AutoCompleteBoxDemo.axaml, demo/Ursa.Demo/Pages/AutoCompleteBoxDemo.axaml.cs, demo/Ursa.Demo/ViewModels/AutoCompleteBoxDemoViewModel.cs, demo/Ursa.Demo/ViewModels/MainViewViewModel.cs, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, src/Ursa.Themes.Semi/Behaviors/ClassHelper.cs, src/Ursa.Themes.Semi/Controls/AutoCompleteBox.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa/Controls/AutoCompleteBox/AutoCompleteBox.cs
Almost identical to native AutoCompleteBox, but more like ComboBox.
=> New control: AutoCompleteBox 

demo/Ursa.Demo/Pages/PaginationDemo.axaml, src/Ursa.Themes.Semi/Controls/Pagination.axaml, src/Ursa/Controls/Pagination/Pagination.cs, src/Ursa/Controls/Pagination/PaginationButton.cs
=> Pagination new Theme: TinyPagination

src/Ursa/Controls/TitleBar/TitleBar.cs
Cloeses #344
Please help to review @LiuChao19940201 @Soar360
=> feat: disable titlebar double tap event when CanResize is false.

demo/Ursa.Demo/Pages/IconButtonDemo.axaml, src/Ursa.Themes.Semi/Controls/IconButton.axaml
1. Add outline theme
2. Fix disabled background 
Close #362
=> Iconbutton improvements

demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml, demo/Ursa.Demo/ViewModels/NumericUpDownDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/KeyGestureInput.axaml, src/Ursa.Themes.Semi/Controls/NumericUpDown.axaml, src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
1. add InnerRightContent to NumericUpDown
2. Add Small/Large size classes.
3. Use shared close button theme in Semi.Avalonia.
Close #363
=> NumericUpDown family updates

demo/Ursa.Demo/Pages/MultiComboBoxDemo.axaml, src/Ursa.Themes.Semi/Controls/MultiComboBox.axaml
=> remove default width in MultiComboBox

demo/Ursa.Demo/Pages/DialogDemo.axaml, demo/Ursa.Demo/ViewModels/DialogDemoViewModel.cs, src/Ursa/Controls/Dialog/Dialog.cs, src/Ursa/Controls/Dialog/DialogWindow.cs, src/Ursa/Controls/Dialog/Options/DialogOptions.cs
And make sure it can be disabled.
=> Introduce CanDragMove to DialogWindow options.

demo/Ursa.Demo/Pages/FormDemo.axaml, src/Ursa.Themes.Semi/Controls/Form.axaml, src/Ursa.Themes.Semi/Converters/FormContentHeightToAlignmentConverter.cs, src/Ursa.Themes.Semi/Converters/FormContentHeightToMarginConverter.cs
1. add AccessKey support for form item.
2. Support label positioning for different content height.
3. polish demo.
Closes #377 
Closes #272
=> Updates to FormItem label and A11y

demo/Ursa.Demo/Pages/DialogDemo.axaml, demo/Ursa.Demo/Pages/DrawerDemo.axaml, demo/Ursa.Demo/ViewModels/DialogDemoViewModel.cs, demo/Ursa.Demo/ViewModels/DrawerDemoViewModel.cs, demo/Ursa.Demo/Views/MainWindow.axaml, src/Ursa.Themes.Semi/Controls/Dialog.axaml, src/Ursa.Themes.Semi/Controls/Drawer.axaml, src/Ursa.Themes.Semi/Controls/Resizer.axaml, src/Ursa.Themes.Semi/Themes/Shared/Dialog.axaml, src/Ursa/Controls/Dialog/Dialog.cs, src/Ursa/Controls/Dialog/DialogControlBase.cs, src/Ursa/Controls/Dialog/DialogWindow.cs, src/Ursa/Controls/Dialog/Options/DialogOptions.cs, src/Ursa/Controls/Dialog/Options/OverlayDialogOptions.cs, src/Ursa/Controls/Dialog/OverlayDialog.cs, src/Ursa/Controls/Drawer/CustomDrawerControl.cs, src/Ursa/Controls/Drawer/DefaultDrawerControl.cs, src/Ursa/Controls/Drawer/Drawer.cs, src/Ursa/Controls/Drawer/DrawerControlBase.cs, src/Ursa/Controls/Drawer/Options/DrawerOptions.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Shared.cs, src/Ursa/Controls/OverlayShared/OverlayFeedbackElement.cs, src/Ursa/Controls/Resizers/DialogResizer.cs, src/Ursa/Controls/Resizers/DialogResizerThumb.cs, src/Ursa/Controls/Resizers/ResizeDirection.cs
This PR brings CanResize feature to Ursa OverlayDialog and Drawer.
=> Introduce Resize feature to Dialog and Drawer. 

src/Ursa.Themes.Semi/Themes/Dark/DatePicker.axaml, src/Ursa.Themes.Semi/Themes/Light/DatePicker.axaml
=> Fix CalenderDayNotCurrentMonthForeground color

src/Ursa/Controls/Dialog/OverlayDialog.cs
DataContext repeated assignment
=> DataContext Repeated assignment

src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
=> Respect OffScreenMargin for elements in chrome layer.

demo/Ursa.Demo/Views/MainWindow.axaml.cs, src/Ursa/Windows/UrsaWindow.cs
Accidently closed 431, continue here.
=>  Add CanClose hook for UrsaWindow

src/Ursa.Themes.Semi/Controls/DateRangePicker.axaml
=> feat: remove redundant border thickness.

src/Ursa/Windows/UrsaWindow.cs, tests/HeadlessTest.Ursa/Controls/UrsaWindowTests/UrsaWindowTest.cs, tests/HeadlessTest.Ursa/Controls/UrsaWindowTests/UrsaWindowWithCloseInference.axaml, tests/HeadlessTest.Ursa/Controls/UrsaWindowTests/UrsaWindowWithCloseInference.axaml.cs
@rabbitism Thanks for your headless test. I added `return` after L119 and the tests passed.
Fixed: #460
=> UrsaWindow Only trigger `Closing` event once when click Close Button

src/Package.props
revert Avalonia dependency from 11.1.4 to 11.1.1
=> Revert dependency.

src/Ursa/Controls/PinCode/PinCode.cs, tests/HeadlessTest.Ursa/Controls/PinCodeTests/PasteTest.cs, tests/HeadlessTest.Ursa/Controls/UrsaWindowTests/UrsaWindowTest.cs
Note: only support paste all, cannot paste from selected cell. 
Close #466
=> PinCode support paste

src/Ursa.Themes.Semi/Controls/Calendar.axaml, src/Ursa.Themes.Semi/Themes/Dark/DatePicker.axaml, src/Ursa.Themes.Semi/Themes/HighContrast/DatePicker.axaml, src/Ursa.Themes.Semi/Themes/Light/DatePicker.axaml
=> Polish day button foreground when in range.

.github/workflows/pack.yml, demo/Directory.Build.props
feat: 1. add bold font in web demo.
2. update demo avalonia version to 11.2.1
3. add nuget publish action.
=> Upgrade demo to 11.2.1

src/Ursa/Common/Constants.cs, src/Ursa/Controls/Dialog/Dialog.cs, src/Ursa/Controls/Dialog/OverlayDialog.cs, src/Ursa/Controls/Drawer/Drawer.cs, src/Ursa/Controls/MessageBox/MessageBox.cs
Somehow collection expression is still not recognized in some environement (Loongson .NET SDK e.t.c). So revert to use explicit char array.
=> Revert collection expression.

src/Ursa/Controls/Pagination/Pagination.cs
Modify the 208th line of code，‘AddHandler’ to ‘RemoveHandler’
=> fix error in Pagination.cs

src/Ursa/Controls/DateTimePicker/DateTimePicker.cs, src/Ursa/Controls/DateTimePicker/TimePicker.cs, src/Ursa/Controls/DateTimePicker/TimeRangePicker.cs, tests/HeadlessTest.Ursa/Controls/FormTests/Dynamic_Item_Generation/Test.cs
=> Fix various nullable issue.

demo/Sandbox/Views/MainWindow.axaml, src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
=> Fix numeric family focus issue.

.github/workflows/deploy.yml, .github/workflows/pack-nightly.yml, .github/workflows/pack.yml, .github/workflows/publish.yml, .github/workflows/release-tag.yml, .github/workflows/test.yml
- manually trigger pack, publish & deploy workflows.
- add pack-nightly & release-tag workflow.
=> Enhance Workflow

src/Ursa.Themes.Semi/Styles/UrsaWindow.axaml, src/Ursa.Themes.Semi/Styles/_index.axaml
=> fix: add margin to topright notification and toast.

demo/Ursa.Demo/Pages/BannerDemo.axaml, src/Ursa/Controls/AutoCompleteBox/AutoCompleteBox.cs, src/Ursa/Controls/Avatar/Avatar.cs, src/Ursa/Controls/Banner/Banner.cs, tests/HeadlessTest.Ursa/Controls/AutoCompleteBoxTests/Tests.cs, tests/HeadlessTest.Ursa/Controls/BannerTests/Tests.cs, tests/HeadlessTest.Ursa/HeadlessTest.Ursa.csproj, tests/HeadlessTest.Ursa/TestAppBuilder.cs, tests/Test.Ursa/AutoCompleteBoxTests/Tests.cs
Fix various issues from failed tests.
=> Add tests for AutoCompleteBox and Banner

demo/Sandbox/Views/MainWindow.axaml, demo/Sandbox/Views/MainWindow.axaml.cs, demo/Sandbox/Views/PW.axaml, demo/Sandbox/Views/PW.axaml.cs, src/Ursa/Controls/Drawer/DrawerControlBase.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs, src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs, src/Ursa/Controls/OverlayShared/OverlayFeedbackElement.cs, tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseEventTest.cs, tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseTestPopupControl.axaml, tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseTestPopupControl.axaml.cs, tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseTestPopupControlVM.cs
=> Fixed: Other windows closing due to error in handling the Drawer close event.

demo/Ursa.Demo/Pages/PathPickerDemo.axaml, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, src/Ursa.Themes.Semi/Controls/PathPicker.axaml, src/Ursa/Controls/PathPicker/PathPicker.cs
=> Path Picker Semi Theme improvement

demo/Ursa.Demo/Pages/IconButtonDemo.axaml, demo/Ursa.Demo/ViewModels/IconButtonDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/IconButton.axaml, src/Ursa.Themes.Semi/Themes/Shared/IconButton.axaml, src/Ursa.Themes.Semi/Themes/Shared/_index.axaml, src/Ursa/Controls/Buttons/IconButton.cs
=> Redesign Iconbutton

src/Ursa.Themes.Semi/Controls/Banner.axaml
This PR ensure Border respect parent `CornerRadius`. Also ensure `Bordered` class won't impact CornerRadius local value.
=> Add corner to banner

src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs
=> Set drawer max size on container size change.

demo/Ursa.Demo/Pages/DialogDemo.axaml, src/Ursa/Controls/IPv4Box/IPv4BoxInputMethodClient.cs, src/Ursa/Controls/Marquee/Marquee.cs, src/Ursa/Controls/PathPicker/PathPicker.cs, tests/HeadlessTest.Ursa/Controls/DateTimePicker/DatePickerTests.cs, tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseEventTest.cs, tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseTestPopupControl.axaml.cs, tests/HeadlessTest.Ursa/Controls/DrawerTests/MeasureTest/DrawerMeasureTest.cs, tests/HeadlessTest.Ursa/Controls/PaginationTests/PaginationTests.cs
=> Clean up warning and non-library issues

src/Ursa.Themes.Semi/Controls/MultiComboBox.axaml
Close #611
Please help to Review @rabbitism
=> fix: MultiComboBox ScrollViewer Issue

src/Ursa.Themes.Semi/Controls/Dialog.axaml, src/Ursa.Themes.Semi/Controls/Drawer.axaml
It will be easy to disable scrollbar after this change.
=> Dialog/Drawer: Make ScrollBarVisibility a parent property

src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml, src/Ursa/Controls/TitleBar/TitleBar.cs, src/Ursa/Controls/TitleBar/WindowThumb.cs
An abstract control to achieve Window DragMove and DoubleTap.
TitleBar background is also replaced by this new control to simplify code.
=> Window Thumb

src/Ursa.Themes.Semi/Controls/UrsaView.axaml, src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml, src/Ursa/Windows/UrsaView.cs, src/Ursa/Windows/UrsaWindow.cs
This pull request includes several updates to improve the functionality and customization of `UrsaView` and `UrsaWindow` components in the Ursa project. The primary changes involve adding new properties for better control over UI elements and enhancing the dialog host management within these components.
* **Dialog Host Management:**
- Added `PART_DialogHost` constant and updated control templates to include named dialog host parts for both `UrsaView` and `UrsaWindow`. This change allows for better identification and management of dialog hosts within the control templates. [[1]](diffhunk://#diff-a2efa86b685c6f0335f228f083a8c71e1eeea5a26c83fb2ee3a73881e765175cL41-R41) [[2]](diffhunk://#diff-376c2033beb2655980bc77fdd7d6a271d31c43426413d9e0a691b806a16dc640L77-R80) …
=> Make UrsaWindow/UrsaView's built in OverlayDialogHost part of logical tree. 

src/Ursa.Themes.Semi/Controls/Badge.axaml
---
Fixes irihitech/Ursa.Avalonia#648
=> feat: add HeaderTemplate binding to Badge control

demo/Ursa.Demo/Pages/BadgeDemo.axaml, demo/Ursa.Demo/Pages/BadgeDemo.axaml.cs, demo/Ursa.Demo/ViewModels/BadgeDemoViewModel.cs, src/Ursa/Controls/Badge/Badge.cs
=> Fix various badge layout issues. 

demo/Ursa.Demo/Pages/PopConfirmDemo.axaml, demo/Ursa.Demo/Pages/PopConfirmDemo.axaml.cs, demo/Ursa.Demo/ViewModels/MainViewViewModel.cs, demo/Ursa.Demo/ViewModels/MenuViewModel.cs, demo/Ursa.Demo/ViewModels/PopConfirmDemoViewModel.cs, src/Ursa.Themes.Semi/Controls/PopConfirm.axaml, src/Ursa.Themes.Semi/Controls/_index.axaml, src/Ursa.Themes.Semi/Themes/Dark/PopConfirm.axaml, src/Ursa.Themes.Semi/Themes/Dark/_index.axaml, src/Ursa.Themes.Semi/Themes/Light/PopConfirm.axaml, src/Ursa.Themes.Semi/Themes/Light/_index.axaml, src/Ursa.Themes.Semi/Themes/Shared/PopConfirm.axaml, src/Ursa.Themes.Semi/Themes/Shared/_index.axaml, src/Ursa/Controls/PopConfirm/PopConfirm.cs, src/Ursa/Controls/PopConfirm/PopConfirmTriggerMode.cs
A port of Semi Design to Avalonia. 
Key differences: in Semi Design onConfirm and onCancel are Promise delegate which is not a good practice in xaml world. In Ursa it is designed to be ICommand. 
It has basic support for async command.
=> New Control: PopConfirm

src/Ursa/Controls/Badge/Badge.cs
* Changed the badge container type from `Border` to `Control`, allowing for more flexibility in the badge's visual structure (`src/Ursa/Controls/Badge/Badge.cs`). [[1]](diffhunk://#diff-7bad76c9efe1a2e5ab45f9b1bc0d4e6d6f0e332f14877de5743a7a1fcb1854a2L11-L86) [[2]](diffhunk://#diff-7bad76c9efe1a2e5ab45f9b1bc0d4e6d6f0e332f14877de5743a7a1fcb1854a2L98)
* Introduced XML documentation for all public properties, methods, and the class itself, improving code readability and maintainability.
=> Relax TemplatePart usage of Badge

.github/workflows/deploy.yml, .github/workflows/pack-nightly.yml, .github/workflows/pack.yml, .github/workflows/publish.yml, .github/workflows/release-tag.yml, .github/workflows/test.yml, Ursa.sln
This pull request includes several updates to GitHub Actions workflows and the solution file to improve consistency, simplify paths, and enhance functionality. Key changes include standardizing file paths in workflows, updating input parameters for better clarity, and adding workflow files to the solution for better visibility.
* **Standardized paths in GitHub Actions workflows**:
- Removed leading `./` and unified paths across workflows for consistency (e.g., `./src/Ursa` changed to `src/Ursa`, `./publish` changed to `publish`). [[1]](diffhunk://#diff-b7397ac12855111bbd97549b21f79120382d72a4bea15d1ac98bfae19eb5b955L48-R72) [[2]](diffhunk://#diff-b673e85d14ea92c37f0edc1b8bb94ae85148a2a12358eb8caffc4f0a8f5d15f4L36-R57) [[3]](diffhunk://#diff-78ca2a162e43bc38ce9cf9eee54d1bfa9b15678fcc153cc55 …
=> Simplify actions

demo/Ursa.Demo/Pages/IconButtonDemo.axaml, src/Ursa.Themes.Semi/Controls/IconButton.axaml
This pull request introduces updates to the `IconButton` component, focusing on improving alignment, theming, and styling. It also makes enhancements to the demo page for better visualization of the component's capabilities. The most important changes are grouped into updates to the demo page and improvements to the `IconButton` control's styling and behavior.
* Added `HorizontalAlignment="Left"` to multiple `IconButton` instances in `IconButtonDemo.axaml` to ensure consistent alignment across the demo. [[1]](diffhunk://#diff-5e25549c5f838a7362425f8732fc9c7d664a6e08a3ca673e2cdd4a9eb6fc93b9R112-R124) [[2]](diffhunk://#diff-5e25549c5f838a7362425f8732fc9c7d664a6e08a3ca673e2cdd4a9eb6fc93b9R136)
* Updated `ControlTheme` in `IconButton.axaml` to include additional properties like …
=> enhance IconButton styles and add new button examples

demo/Ursa.Demo/Pages/DualBadgeDemo.axaml, src/Ursa.Themes.Semi/Controls/DualBadge.axaml, src/Ursa.Themes.Semi/Themes/Dark/DualBadge.axaml, src/Ursa.Themes.Semi/Themes/Light/DualBadge.axaml, src/Ursa.Themes.Semi/Themes/Shared/DualBadge.axaml
This pull request introduces updates to the `DualBadge` component across multiple files, focusing on simplifying its structure, improving its design, and removing redundant resources. The changes streamline the implementation, enhance maintainability, and ensure consistency in the usage of the `DualBadge` component.
* [`demo/Ursa.Demo/Pages/DualBadgeDemo.axaml`](diffhunk://#diff-ff1814f2adc7ca623f2f2c82da39b8e35f3bfaa98a917acc7476c02b965c074dL22-R49): Simplified `DualBadge` usage by consolidating properties (`Content`, `Header`, `Icon`) into a single declaration for each badge instance, replacing the previous nested structure.
* [`src/Ursa.Themes.Semi/Controls/DualBadge.axaml`](diffhunk://#diff-877076acba964339afb5dba1d044c80023ab5dd15daa8ec996308a80b810d78aR6-R54): Added a design preview …
=> enhance DualBadge styles

Ursa.sln, src/Package.props, src/Ursa/Controls/IPv4Box/IPv4Box.cs, src/Ursa/Controls/IPv4Box/IPv4BoxInputMethodClient.cs
implement two selection related features to avoid app crash. 
Closes #714
=> Try to fix android ime crash

src/Ursa/Controls/PopConfirm/PopConfirm.cs, src/Ursa/Controls/TitleBar/WindowThumb.cs
=> Fix nullable annotations in popconfirm

demo/Ursa.Demo/Pages/ElasticWrapPanelDemo.axaml, src/Ursa/Controls/ElasticWrapPanel.cs, tests/HeadlessTest.Ursa/Controls/ElasticWrapPanelTests/Tests.cs
This property help user to make a special arrangement when there is only one line of items.
=> Add new readonly property: LineCount for ElasticWrapPanel

demo/Ursa.Demo/Pages/ImageViewerDemo.axaml, demo/Ursa.Demo/Pages/ImageViewerDemo.axaml.cs, src/Ursa/Controls/ImageViewer/ImageViewer.cs
修复 https://github.com/irihitech/Ursa.Avalonia/issues/680
=> 修复 ImageViewer.Source 设置为null会报错的问题

src/Ursa/Controls/IPv4Box/IPv4Box.cs, src/Ursa/Controls/PinCode/PinCode.cs, src/Ursa/Controls/TimeBox.cs
https://github.com/irihitech/Ursa.Avalonia/issues/590
=> 修复 IPv4Box PinCode TimeBox  对 Delete 键的支持
