irihitech/Ursa.Avalonia

- demo/Ursa.Demo/Models/MenuKeys.cs
- demo/Ursa.Demo/Pages/IconButtonDemo.axaml
- demo/Ursa.Demo/Pages/IconButtonDemo.axaml.cs
- demo/Ursa.Demo/ViewModels/IconButtonDemoViewModel.cs
- demo/Ursa.Demo/ViewModels/MainViewViewModel.cs
- demo/Ursa.Demo/ViewModels/MenuViewModel.cs
- src/Ursa.Themes.Semi/Controls/IconButton.axaml
- src/Ursa.Themes.Semi/Controls/_index.axaml
- src/Ursa/Common/IconPlacement.cs
- src/Ursa/Controls/IconButton.cs
> New Control: Icon Button

- demo/Ursa.Demo/Models/MenuKeys.cs
- demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml
- demo/Ursa.Demo/Pages/NumericUpDownDemo.axaml.cs
- demo/Ursa.Demo/ViewModels/MainViewViewModel.cs
- demo/Ursa.Demo/ViewModels/MenuViewModel.cs
- demo/Ursa.Demo/ViewModels/NumericUpDownDemoViewModel.cs
- src/Ursa.Themes.Semi/Controls/NumericUpDown.axaml
- src/Ursa.Themes.Semi/Controls/_index.axaml
- src/Ursa/Controls/NumericUpDown/IntUpDown.cs
- src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
- src/Ursa/Controls/NumericUpDown/ValueChangedEventArgs.cs
1. This bunch of controls utilize only one template but supports type safe control for every built in C# primitive number types. 
2. It supports Byte, SByte, Short, UShort, Int, UInt, Long, ULong, Float, Double, Decimal
3. Value is nullable but supports empty input fallback value.
4. When set `AllowDrag` = true, it supports dragging to change values. DoubleClick on textbox will enter edit mode, Esc or lost focus will exit edit mode.
> New Control: NumericUpDown family

- src/Ursa/Controls/IPv4Box.cs
Another issue with `IPv4Box`:
``` cs
[ObservableProperty] private IPAddress? _address = IPAddress.Parse("192.168.1.1");
public void ChangeAddress()
{
Address = IPAddress.Parse("192.168.0.1");
}
```
This `ChangeAddress` method will only take effect once.
For example, now it is  `192.168.1.1`.Then I press the button to change it, and this time it will change normally to `192.168.0.1`.But I'll make another change, such as changing it to  `1.1.1.1` Pressing the button will render it ineffective.
> IPAddress DefaultBindingMode

- src/Ursa.Themes.Semi/Themes/Dark/ButtonGroup.axaml
Fixes #140
This PR addresses the issue where the ButtonGroup separator was invisible in dark mode by updating the ButtonGroupSeparatorForeground color to improve visibility. The opacity has been set to 0.08 with a white color to ensure the separator is visible in both light and dark modes.
- Added SolidColorBrush with opacity 0.08 and color white for ButtonGroup separator
- Tested the changes in both light and dark modes to ensure improved visibility
- This fix should resolve the visibility issue in dark mode
- Please review and provide feedback
> Fix: Update ButtonGroup separator color for visibility in dark mode

- src/Ursa/Controls/RangeSlider/RangeSlider.cs
当拖拽时鼠标移动过快，使Thumb重合或无法接近。
以拖拽Upper Thumb为例
鼠标移动过快，会造成上一帧鼠标还在Upper thumb，而下一帧已经在Lower thumb左侧，使Line 216 中的``` _currentThumb != thumb```提前触发而return掉。
所以加了一个判断，如果是在拖拽状态，让thumb 等于 _currentThumb，这样就可以确保拖拽中途不会发生``` _currentThumb != thumb```的情况。
但这样会产生一个Bug，当拖拽Lower thumb使其与Upper thumb在slider最右侧重合时，因为Upper thumb的图层在Lower thumb之上，会导致无法调节的情况。而且也会出现Lower value大于Upper value或Upper value 小于 Lower value的情况。
我的解决办法：
SetCurrentValue时，顺带检查是否存在Lower value大于Upper value或Upper value 小于 Lower value的情况，然后将Lower value（或Upper value）修正。
> 修复RangeSlider中，因鼠标移动速度过快而使Thumb无法重合的问题

- demo/Ursa.Demo/Pages/TagInputDemo.axaml
- src/Ursa/Controls/TagInput/LostFocusBehavior.cs
- src/Ursa/Controls/TagInput/TagInput.cs
https://github.com/irihitech/Ursa.Avalonia/assets/3275834/51715d50-9d2c-47a3-b4d9-3626807bceb7
当用户输入数据后未删除也没有回车使数据生效时，需要提供一个方式可以清理未生效的数据
> TagInput 增加 CleanLostFocus 用于失去焦点后清空TextBox数据

- src/Ursa/Controls/TagInput/TagInput.cs
When TagInput's Tags changed, you want remove all the tags except the textBox from `Items` collection, right? But the code does not do that.
old code:
```cs
for (int i = 0; i < Items.Count - 1; i++)
{
Items.RemoveAt(Items.Count - 1);
}
```
Items.Count will change after every `RemoveAt` so If the `Items.Count` is 6, It only remove 3 times, then `i` will be 3,`Items.Count` will be 3, the loop will end.
So, I fix this problem.
new code:
```cs
// remove all tags except the textbox
int count = Items.Count;
for (int i = 0; i < count - 1; i++)
{
Items.RemoveAt(0);
}
```
I create a repro branch(https://github.com/dameng324/Ursa.Avalonia/tree/taginput-fix-tags-changed-repo) to repro this problem. Feel free to check it.
> fix TagInput bug when TagsProperty changed.

- demo/Ursa.Demo/Views/MainView.axaml
- src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
- src/Ursa/Controls/Dialog/Options/OverlayDialogOptions.cs
- src/Ursa/Controls/Dialog/OverlayDialog.cs
- src/Ursa/Controls/Drawer/Drawer.cs
- src/Ursa/Controls/Drawer/Options/DrawerOptions.cs
- src/Ursa/Controls/MessageBox/MessageBox.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Shared.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogManager.cs
1. Support register host with same ID as long as they are in different toplevels. 
2. Add TopLevelHashCode to overlay related options, allow user to assign a toplevle hash code. 
3. Obsolete `HasModal` attribute, replace by `IsInModalStatus`.
4. Allow to set any control as ModalStatusScope.
5. Support propagating IsInModalStatus to visual ancestor that is ModalStatusScope. 
Closes:
Closes #281 
Closes #282
> OverlayDiaogHost refatoring

- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Shared.cs
or the mask will cover entire window, and cannot be closed if dialog close button is outside of screen.
> Make mask draggable when it's modal and cannot light dismiss.

- src/Ursa/Controls/Breadcrumb/Breadcrumb.cs
- src/Ursa/Controls/Breadcrumb/BreadcrumbItem.cs
This PR attempts to add support for a command parameter for `BreadcrumbItem`, and its binding for `Breadcrubm`. The added property allows user code to distinguish between breadcrumb items when binding a Command to a common command located in the DataContext, by passing data from each breadcrumb item through the binding of `CommandParameter` / `CommandParameterBinding`.
---
This PR does not change the sample code in the demo, which should also work without any changes.
To test the scenario demonstrated above, it's possible to apply the patch below:
<details>
<summary>Patching code</summary>
```diff
Index: demo/Ursa.Demo/Pages/BreadcrumbDemo.axaml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8 …
```
> feat: Breadcrumb and its item may support CommandParameter/Binding

- demo/Ursa.Demo/Pages/MultiComboBoxDemo.axaml
- src/Ursa.Themes.Semi/Controls/MultiComboBox.axaml
- src/Ursa/Controls/ComboBox/MultiComboBox.cs
~~This PR attempts to add support for a placeholder similar to `ComboBox` for `MultiComboBox`.~~
~~The control theme of `ComboBox` in Semi.Avalonia does not respect the `PlaceholderForeground` property, so this PR also does not add the `PlaceholderForeground` property for the `MultiComboBox`.~~
Newly added property is renamed to `Watermark`. Details can be found below.
---
---
```diff
+ MultiComboBox.WatermarkProperty
+ MultiComboBox.Watermark
```
No breaking changes will be introduced.
> feat: MultiComboBox may support placeholder (watermark)

- demo/Ursa.Demo/Pages/MultiComboBoxDemo.axaml
- demo/Ursa.Demo/ViewModels/MultiComboBoxDemoViewModel.cs
- src/Ursa.Themes.Semi/Controls/MultiComboBox.axaml
- src/Ursa/Controls/ComboBox/MultiComboBox.cs
- src/Ursa/Controls/ComboBox/MultiComboBoxItem.cs
1. Update container selection state immediately after collection updated. 
2. Add popup slot.
3. fix various binding relative resource issue.
4. update empty pseudo-class handing, simplify watermark visibility.
---
Note: Avalonia Native ComboBox can also be invoked by right click. I will keep this behavior.
> Fix various issues for MultiComboBoxItem

- src/Ursa/Controls/MessageBox/MessageBox.cs
This is to match the WPF MessageBox default behavior.
No binary breaking change, but behavior change.
> Change messagebox default button param to `OK`

- src/Ursa.Themes.Semi/Locale/en-us.axaml.cs
This is a temporary fix because XAMLX ignores empty string resource.
Should be reverted after https://github.com/AvaloniaUI/Avalonia/issues/16659 is resolved.
> Fix empty resource issue in en-US localization dictionary. 

- demo/Ursa.Demo/Pages/TimePickerDemo.axaml
- demo/Ursa.Demo/ViewModels/TimePickerDemoViewModel.cs
- src/Ursa.Themes.Semi/Controls/TimePicker.axaml
- src/Ursa.Themes.Semi/Controls/TimeRangePicker.axaml
- src/Ursa/Controls/DateTimePicker/TimeChangedEventArgs.cs
- src/Ursa/Controls/DateTimePicker/TimePicker.cs
- src/Ursa/Controls/DateTimePicker/TimePickerPresenter.cs
- src/Ursa/Controls/DateTimePicker/TimeRangePicker.cs
This PR is to fix timepicker initialization issue. 
1. for easier handling, TimePicker.SelectedTimeChanged event is now routed event, a new EventArg is created for this event. 
2. Instead of directly binding to template parent, TimePicker now handles presenter time in code behind. 
3. Extract TimeToText process and call it once after template applied. 
4. DisplayFormat now triggers text update immediately for TimeRangePicker.
> Fix Timepicker issues

- src/Ursa/Controls/ThemeSelector/ThemeSelectorBase.cs
- src/Ursa/Controls/ThemeSelector/ThemeToggleButton.cs
close #340 
1. Remove _scope variable in ThemeSelectorBase, only use TargetScope
2. When `ThemeToggleButton` is in `Indicator` mode or not enabled `IsThreeState`, the button is only available for Light mode and Dark mode switch
3. When `ThemeToggleButton` is in `Controller` mode and enabled `IsThreeState`, the theme will switch following the order: Default, Light, Dark
4. Remove the null check for setting the default pseudo class in `OnButtonClicked` because `SelectedTheme` will always have a value
5. add special check in `SyncThemeFromScope` when `IsThreeState` not enabled and theme is null, setting the default to Light theme
> refactor ThemeSelectorBase and ThemeToggleButton

- src/Ursa/Controls/Dialog/DialogControlBase.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs
1. make full-screen dialog draggable to trigger window moving
2. Make sure full-screen is always full-screen when resizing window.
> FullScreen overlay dialog updates

- src/Ursa/Controls/TitleBar/CaptionButtons.cs
Closes #394 
Notice: the inner rule still has a higher priority, like Minimize button is still invisible when fullscreen, even if you explicitly set it as visible.
> Fix: Caption buttons should update visibility upon UrsaWindow property change. 

- src/Ursa.Themes.Semi/Controls/Dialog.axaml
- src/Ursa.Themes.Semi/Controls/MessageBox.axaml
- src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
in some environment (well ubuntu), borderless window is not possible. So it is necessary to expose border customization for user. User can now globally add border brush and border thickness to UrsaWindow, DialogWindow, DefaultDialogWindow and MesageBox.
> Enable UrsaWindow and Dialog border customization.

- demo/Ursa.Demo/Pages/TreeComboBoxDemo.axaml
- demo/Ursa.Demo/ViewModels/TreeComboBoxDemoViewModel.cs
- src/Ursa.Themes.Semi/Controls/TreeComboBox.axaml
- src/Ursa/Controls/ComboBox/TreeComboBox.cs
- src/Ursa/Controls/ComboBox/TreeComboBoxItem.cs
TreeComboBox now exposes a property to control whether the node is selectable.
If selectable, then selectable (
If not selectable, user can only click on expander chevron to expand and collapse the node,
> Introduce IsSelectable for TreeComboBoxItem.

- src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Shared.cs
Behaviors that interacts with top level window will only be enabled when you set this flag to true. Including:
* Drag Window with overlay mask
* Drag Window with full screen dialog
Any host can be IsToplevel = true, it doesn't have to be in the window template.
> Introduce IsTopLevel to OverlayDialogHost

- src/Ursa.Themes.Semi/Controls/Resizer.axaml
- src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
- src/Ursa.Themes.Semi/Controls/_index.axaml
- src/Ursa.Themes.Semi/Themes/Shared/Resizer.axaml
- src/Ursa.Themes.Semi/Themes/Shared/_index.axaml
- src/Ursa/Controls/Resizers/ResizeDirection.cs
- src/Ursa/Controls/Resizers/WindowResizer.cs
- src/Ursa/Controls/Resizers/WindowResizerThumb.cs
- src/Ursa/Windows/UrsaWindow.cs
In some Linux env, borderless Window must consume `SystemDecorations=None`, but this will disable window resizing. This PR introduce WindowResizer, and a new property `IsManagedRezierVisible` in UrsaWindow, so user can enable resizing without SystemDecoration border.
> Introduce Resizer for UrsaWindow

- .github/workflows/pack.yml
- src/Ursa.PrismExtension/Ursa.PrismExtension.csproj
- src/Ursa.ReactiveUI/Ursa.ReactiveUIExtension.csproj
- src/Ursa.Themes.Semi/Ursa.Themes.Semi.csproj
1. Add nuget packaging for two extension projects in workflow
2. Enable SourceLink
3. Bump Prism extension for next release.
> Add Nuget packaging for Prism and ReactiveUI extensions

- demo/Ursa.Demo/Pages/LoadingDemo.axaml
- src/Ursa.Themes.Semi/Controls/Loading.axaml
- src/Ursa/Controls/Loading/Loading.cs
- src/Ursa/Controls/Loading/LoadingContainer.cs
- src/Ursa/Controls/Loading/LoadingIcon.cs
Close #413 
Close #414
Also fix LoadingContainer not terminate animation properly, by introducing IsLoading property to LoadingIcon, and use this property to control animation.
> Introducing background and foreground for LoadingContainer

- src/Package.props
The current built artifact health info:
Setting `ContinuousIntegrationBuild` to `true` will enable deterministic builds feature.
See:
- [ContinuousIntegrationBuild - MSBuild properties for Microsoft.NET.Sdk - .NET | Microsoft Learn](https://learn.microsoft.com/dotnet/core/project-sdk/msbuild-props#continuousintegrationbuild)
- [Source Link and .NET libraries - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink#:~:text=CONSIDER%20enabling%20deterministic%20builds.)
> ✔️ CONSIDER enabling deterministic builds.
> Enables Deterministic Builds

- src/Ursa/Controls/DateTimePicker/DatePicker.cs
- src/Ursa/Controls/DateTimePicker/DateRangePicker.cs
1. DatePicker popup was immediately closed when clicking on Month/Year switch. This is fixed. 
2. DateRangePicker could not be closed when tab out. This is fixed.
> Fix DatePicker and DateRangePicker behaviour

- src/Ursa/Controls/EnumSelector/EnumSelector.cs
- src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
Since we're targeting for `netstandard2.0`/`net8.0`, update to `#if NET` to avoid changes in future target framework updates
> update compile condition

- src/Ursa/Controls/OverlayShared/OverlayFeedbackElement.cs
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Case_Close_Dialog_Clear_Content_Parent/Test.cs
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Case_Close_Dialog_Clear_Content_Parent/TestWindow.axaml
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Case_Close_Dialog_Clear_Content_Parent/TestWindow.axaml.cs
TView should be returned to the user instead of its parent after the dialog is closed.
> Fixed: Closing a dialog returns TView to the user instead of occupying its parent.

- src/Ursa/Controls/ComboBox/MultiComboBoxItem.cs
Current behavior
The items of mutiselectcombo can not be accessed by UIAutomation.
> Accessibility suppport for MultiComboItem

- demo/Ursa.Demo/Dialogs/CustomDemoDialog.axaml
- src/Ursa/AssemblyInfo.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs
- src/Ursa/Controls/OverlayShared/OverlayDialogHost.Drawer.cs
- src/Ursa/Helpers/FocusHelper.cs
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/FocusDialog.axaml
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/FocusDialog.axaml.cs
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/NormalDialog.axaml
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/NormalDialog.axaml.cs
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/Test.cs
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/TestWindow.axaml
- tests/HeadlessTest.Ursa/Controls/OverlayShared/Dialog_Primary_Focus/TestWindow.axaml.cs
User can set `FocusHelper.DialogFocusHint` on an InputElement. **Modal Overlay Dialog** and **Modal Drawer** will try to focus this element. if User doesn't set any, the first focusable (root border of dialog container) will be focused by default. 
XAML sample:
```xaml
<TextBox Text="Hello" u:FocusHelper.DialogFocusHint="True"></TextBox>
```
> Allow user to set Modal Dialog initial focus element

- demo/Ursa.Demo/Pages/AspectRatioLayoutDemo.axaml
- demo/Ursa.Demo/Pages/AspectRatioLayoutDemo.axaml.cs
- demo/Ursa.Demo/ViewModels/AspectRatioLayoutDemoViewModel.cs
- demo/Ursa.Demo/ViewModels/MainViewViewModel.cs
- demo/Ursa.Demo/ViewModels/MenuViewModel.cs
- global.json
- src/Ursa/Controls/AspectRatioLayout/AspectRatioLayout.cs
- src/Ursa/Controls/AspectRatioLayout/AspectRatioLayoutItem.cs
- src/Ursa/Controls/AspectRatioLayout/AspectRatioMode.cs
The control AspectRatioLayout provides a feature to select control layout based on the aspect ratio of the visual area (Bounds).
> Add a new control AspectRatioLayout

- demo/Ursa.Demo/DataTemplates/FormDataTemplateSelector.cs
- demo/Ursa.Demo/Pages/FormDemo.axaml
- demo/Ursa.Demo/ViewModels/FormDemoViewModel.cs
- src/Ursa.Themes.Semi/Controls/Form.axaml
- src/Ursa/Controls/Form/Form.cs
- src/Ursa/Controls/Form/FormGroup.cs
- tests/HeadlessTest.Ursa/Controls/FormTests/Dynamic_Item_Generation/DataTemplateSelector.cs
- tests/HeadlessTest.Ursa/Controls/FormTests/Dynamic_Item_Generation/Test.cs
- tests/HeadlessTest.Ursa/Controls/FormTests/Dynamic_Item_Generation/TestViewModel.cs
- tests/HeadlessTest.Ursa/Controls/FormTests/Dynamic_Item_Generation/TestWindow.axaml
- tests/HeadlessTest.Ursa/Controls/FormTests/Dynamic_Item_Generation/TestWindow.axaml.cs
Allow user define a series of viewmodel types (based on input type) and generate form directly.
> Form Dynamic Generation

- demo/Ursa.Demo/Pages/DialogDemo.axaml
- demo/Ursa.Demo/Pages/DrawerDemo.axaml
- src/Ursa.Themes.Semi/Controls/DatePicker.axaml
- src/Ursa.Themes.Semi/Controls/DateRangePicker.axaml
- src/Ursa.Themes.Semi/Controls/DateTimePicker.axaml
- src/Ursa.Themes.Semi/Controls/Dialog.axaml
- src/Ursa.Themes.Semi/Controls/Drawer.axaml
- src/Ursa.Themes.Semi/Controls/MessageBox.axaml
- src/Ursa.Themes.Semi/Controls/MultiComboBox.axaml
- src/Ursa.Themes.Semi/Controls/TimePicker.axaml
- src/Ursa.Themes.Semi/Controls/TimeRangePicker.axaml
- src/Ursa.Themes.Semi/Controls/TreeComboBox.axaml
- src/Ursa.Themes.Semi/Index.axaml
- src/Ursa.Themes.Semi/Themes/Dark/Dialog.axaml
- src/Ursa.Themes.Semi/Themes/Light/Dialog.axaml
- src/Ursa.Themes.Semi/Themes/Shared/_index.axaml
> Upgrade Ursa-Semi theme to utilize Semi Design 11.2.1 latest design

- src/Ursa/Controls/PinCode/PinCode.cs
- tests/HeadlessTest.Ursa/Controls/PinCodeTests/PasteTest.cs
如果粘贴内容有效，则执行 `CompleteCommand` 并触发 `CompleteEvent` 事件。
#500
> 优化 PinCode 类

- src/Ursa/Controls/TitleBar/CaptionButtons.cs
- src/Ursa/Controls/TitleBar/TitleBar.cs
1. move visual root identification to `AttachedToVisualTree`.
2. Make sure caption buttons are detached when TitleBar is detached.
3. Subscribe and include `:active` pseudo class. (and properly dispose it)
> TitleBar improvement

- .github/workflows/test.yml
- src/Ursa/Controls/ImageViewer/ImageViewer.cs
- tests/Test.Ursa/ImageViewerTests/Stretch_Initial_Value/StretchValueTest.cs
> fix: fix image binding to stretch initialization issue.

- src/Ursa/Controls/IPv4Box/IPv4Box.cs
- src/Ursa/Controls/IPv4Box/IPv4BoxInputMethodClient.cs
This PR partially fix IME issue of IPv4Box on Android. 
Notice: It only enables IME when IPv4Box got focus. If you close IME and click the control again, it still won't work. (Sorry don't know how to fix this issue. PR is welcomed. )
> Enable IME for IPv4Box on android. 

- demo/Ursa.Demo/Pages/PathPickerDemo.axaml
- demo/Ursa.Demo/Pages/PathPickerDemo.axaml.cs
- demo/Ursa.Demo/ViewModels/MainViewViewModel.cs
- demo/Ursa.Demo/ViewModels/MenuViewModel.cs
- demo/Ursa.Demo/ViewModels/PathPickerDemoViewModel.cs
- src/Ursa.ReactiveUIExtension/Ursa.ReactiveUIExtension.csproj
- src/Ursa.Themes.Semi/Controls/PathPicker.axaml
- src/Ursa.Themes.Semi/Controls/_index.axaml
- src/Ursa/Controls/PathPicker/PathPicker.cs
- src/Ursa/Controls/PathPicker/UsePickerTypes.cs
`PathPicker` aggregates file selection functionality and provides a `Command` property. When a button is pressed or Enter is pressed while the focus is on `PathPicker`, the `Command `is triggered and a `Task<IReadOnlyList>` is passed to the `Command`.
> Feat: add a new control PathPicker, add PathPickerDemo

- src/Ursa.Themes.Semi/Index.axaml.cs
- tests/HeadlessTest.Ursa/Semi/LocalizationTest.cs
Follow-up of Semi https://github.com/irihitech/Semi.Avalonia/pull/520
> Add locale switch helper method

- demo/Ursa.Demo/Views/TitleBarRightContent.axaml
- src/Ursa.Themes.Semi/Controls/Calendar.axaml
- src/Ursa.Themes.Semi/Controls/DialogShared.axaml
- src/Ursa.Themes.Semi/Controls/DualBadge.axaml
- src/Ursa.Themes.Semi/Controls/NavMenu.axaml
- src/Ursa.Themes.Semi/Controls/Pagination.axaml
- src/Ursa.Themes.Semi/Controls/ScrollToButton.axaml
- src/Ursa.Themes.Semi/Controls/TagInput.axaml
- src/Ursa.Themes.Semi/Controls/ThemeSelector.axaml
- src/Ursa.Themes.Semi/Themes/Shared/NavigationMenu.axaml
* fix CornerRadius of CloseButton.
* add IsVisible to Content of DualBadge.
* remove Geometry & sys:.
* using InnerPathIcon.
> fix various issues.

- demo/Ursa.Demo/Pages/DatePickerDemo.axaml
- src/Ursa/AssemblyInfo.cs
- src/Ursa/Controls/DateTimePicker/CalendarContext.cs
- src/Ursa/Controls/DateTimePicker/CalendarView.cs
- src/Ursa/Controls/DateTimePicker/CalendarYearButton.cs
- src/Ursa/Controls/DateTimePicker/DatePicker.cs
- src/Ursa/Controls/DateTimePicker/DateTimeHelper.cs
- src/Ursa/Controls/DateTimePicker/DateTimePicker.cs
- src/Ursa/Controls/DateTimePicker/TimePicker.cs
- src/Ursa/Controls/DateTimePicker/TimePickerPresenter.cs
- src/Ursa/Controls/DateTimePicker/TimeRangePicker.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/CalendarDayButtonTests.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/CalendarViewHelper.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/CalendarViewTests.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/CalendarYearButtonTests.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/DatePickerTests.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/TimePickerPresenterTests.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/TimePickerTests.cs
- tests/HeadlessTest.Ursa/Controls/DrawerTests/CloseEventTest/DrawerCloseTestPopupControlVM.cs
- tests/HeadlessTest.Ursa/HeadlessTest.Ursa.csproj
- tests/HeadlessTest.Ursa/TestHelpers/ControlExtensions.cs
- tests/Test.Ursa/DateTimePickerTests/CalendarContextTests.cs
- tests/Test.Ursa/DateTimePickerTests/CalendarDayButtonTests.cs
- tests/Test.Ursa/DateTimePickerTests/DateRangeExtensionTests.cs
- tests/Test.Ursa/DateTimePickerTests/DateRangeTests.cs
- tests/Test.Ursa/DateTimePickerTests/DateTimeHelperTests.cs
1. Add tests
2. make some of the classes internal. 
3. fix issues discovered during testing. 
4. fix TimePicker initialization issue, clicking on TimePicker/TimeRangePicker/DateTimePicker will not trigger a selection immediately, but waiting for user interaction. 
5. fix #571 
1. Editing text in DateRangePicker/TimeRangePicker will not trigger start/end update. Will be fixed in the future.
> Date/Time picker tests and cleanup. 

- demo/Sandbox/App.axaml.cs
- demo/Sandbox/Views/MainSplashWindow.axaml
- demo/Sandbox/Views/MainSplashWindow.axaml.cs
- demo/Ursa.Demo/App.axaml.cs
- demo/Ursa.Demo/ViewModels/SplashViewModel.cs
- demo/Ursa.Demo/Views/MainSplashWindow.axaml
- demo/Ursa.Demo/Views/MainSplashWindow.axaml.cs
- demo/Ursa.Demo/Views/MainWindow.axaml
- demo/Ursa.Demo/Views/MvvmSplashWindow.axaml
- demo/Ursa.Demo/Views/MvvmSplashWindow.axaml.cs
- src/Ursa.Themes.Semi/Controls/SplashWindow.axaml
- src/Ursa.Themes.Semi/Controls/_index.axaml
- src/Ursa/Windows/SplashWindow.cs
This new control is just to simplify the setup of SplashScreen which is commonly used in desktop application. The implementation is simple, just replace the application MainWindow if applicable. 
There is a simple CountDown implementation that handles most commonly used scenario. 
Limitations:
1. Only desktop environment.
2. Prism shell is not supported as it's impossible to change `PrismApplicationBase.MainWindow`.
> Add Splash Window

- demo/Ursa.Demo/Pages/PaginationDemo.axaml
- src/Ursa/Controls/Pagination/Pagination.cs
- tests/HeadlessTest.Ursa/Controls/PaginationTests/PaginationTests.cs
This pull request includes several changes to the pagination functionality in the Ursa project, focusing on improving the handling of the current page and ensuring proper initialization. The most important changes are grouped by theme below.
* Added `CurrentPage="5"` to the `Pagination` control in `PaginationDemo.axaml` to set the default current page in the demo.
* Modified `CoerceCurrentPage` method to only coerce the value if the pagination is initialized, preventing default coercion when `PageCount` is not yet determined.
* Added a check in `OnPageSizeChanged` to return early if the pagination is not initialized, ensuring the page count is only updated when appropriate.
* Updated `OnApplyTemplate` to set `CurrentPage` using `MathHelpers.SafeClamp` and to call …
> Fix pagination initialization issue.

- src/Ursa.Themes.Semi/Controls/Calendar.axaml
- src/Ursa/Controls/DateTimePicker/DatePicker.cs
- src/Ursa/Controls/DateTimePicker/DateRangePicker.cs
- src/Ursa/Controls/DateTimePicker/DateTimePicker.cs
- src/Ursa/Controls/DateTimePicker/TimePicker.cs
- src/Ursa/Controls/DateTimePicker/TimeRangePicker.cs
- tests/HeadlessTest.Ursa/Controls/DateTimePicker/CalendarViewHelper.cs
1. Use IconButton for CalendarView navigation button to reduce their sizes. Thus the overall width can be stable.
2. Fix an issue when DateTimePicker lost focus and triggered a popup racing condition.
> Fix CalendarView style and DateTimePicker frozen issue

- src/Ursa/Controls/ComboBox/MultiComboBox.cs
Closes #598 
Please help to review @fangjiajiajia
> Fix `MultiComboBox.SelectedItemTemplate` datatype annotation

- src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
- src/Ursa/Controls/TitleBar/TitleBar.cs
Introduce a new AttachedProperty: u:TitleBar.IsTitleBarHitTestVisible
Setting this property to false (on u:UrsaWindow) will disable u:TitleBar default "Drag and DoubleTap" behavior.
> Allow setting titlebar HitTest from UrsaWindow

- demo/Ursa.Demo/Pages/ButtonGroupDemo.axaml
- src/Ursa.Themes.Semi/Controls/ButtonGroup.axaml
- src/Ursa.Themes.Semi/Styles/ButtonGroup.axaml
- src/Ursa.Themes.Semi/Themes/Shared/ButtonGroup.axaml
Close #604 
This pull request includes several changes to the `ButtonGroup` component, primarily focusing on improving the layout and styling. The most important changes include updating the `ButtonGroup` layout in the demo page, modifying the `ButtonGroup` control to use dynamic resources, and enhancing the styles for different button sizes.
Improvements to `ButtonGroup` layout:
* [`demo/Ursa.Demo/Pages/ButtonGroupDemo.axaml`](diffhunk://#diff-1d5f3130651d374b935e9e19f1b5c3b9959cc4afecfb144dc71ed1eb69186d36L14-R45): Modified the layout to include additional button groups with different classes and fixed the formatting of `Run` elements inside `TextBlock`.
Enhancements to `ButtonGroup` control:
* [`src/Ursa.Themes.Semi/Controls/ButtonGroup.axaml`](diffhunk://#diff-bf011d004fdb7be67601a555b …
> Fix ButtonGroup Height & Padding issue

- src/Ursa.Themes.Semi/Controls/SplashWindow.axaml
This pull request includes a modification to the `SplashWindow.axaml` file to improve the theme management for the `SplashWindow` control. The change involves using a base theme for the control to inherit default properties, which simplifies the theme definition and ensures consistency.
Theme management improvement:
* [`src/Ursa.Themes.Semi/Controls/SplashWindow.axaml`](diffhunk://#diff-455db7918e2d35200c8af6d9b2e57b5e36cb039c2f8391a453b4798722a433e0L5-R5): Modified the `ControlTheme` for `u:SplashWindow` to be based on the `Window` static resource, removing redundant property setters.
> SplashWindow default theme update. 

- demo/Ursa.Demo/Dialogs/CustomDemoDialog.axaml.cs
- demo/Ursa.Demo/Pages/NotificationDemo.axaml.cs
- demo/Ursa.Demo/ViewModels/MainViewViewModel.cs
- demo/Ursa.Demo/Views/MainView.axaml.cs
- demo/Ursa.Demo/Views/MainWindow.axaml.cs
- src/Ursa/Controls/Notification/WindowNotificationManager.cs
- src/Ursa/Controls/NotificationShared/WindowMessageManager.cs
- src/Ursa/Controls/Toast/WindowToastManager.cs
This pull request includes several changes to improve the handling and management of notifications and toasts in the Ursa application. The changes primarily focus on introducing new methods to retrieve existing notification and toast managers and updating the related code to utilize these methods.
Improvements to notification and toast management:
* [`src/Ursa/Controls/Notification/WindowNotificationManager.cs`](diffhunk://#diff-9a5f3f3eb8c4c01b55dab9b9edcc5e1918ce43bd90bd1f2f8ffee3fdf565d6a8R73-R84): Added the `TryGetNotificationManager` method to retrieve an existing `WindowNotificationManager` from a `Visual` element.
* [`src/Ursa/Controls/Toast/WindowToastManager.cs`](diffhunk://#diff-6a2d72b0a8a41926ded0c64cf816f0baefec10aa557a153cd7f82d822e0ef280R38-R49): Added the …
> Add TryGetXXManager to WindowXXManager

- demo/Ursa.Demo/Pages/NotificationDemo.axaml.cs
- demo/Ursa.Demo/Views/MainView.axaml.cs
This pull request includes changes to improve the initialization of the `NotificationManager` in the `OnAttachedToVisualTree` method for both `NotificationDemo` and `MainView` components. The changes ensure that a new `WindowNotificationManager` is created if the existing one cannot be retrieved, and they handle cases where `topLevel` or `_viewModel` might be null.
Improvements to `NotificationManager` initialization:
* [`demo/Ursa.Demo/Pages/NotificationDemo.axaml.cs`](diffhunk://#diff-ea1134050b280d31ef0ccdd5994035b2a2654d0542bbf2752d8d64cb9dbedba9L23-R27): Modified the `OnAttachedToVisualTree` method to create a new `WindowNotificationManager` if the existing one cannot be retrieved, and added a null check for `topLevel`.
* [`demo/Ursa.Demo/Views/MainView.axaml.cs`](diffhunk://#diff-afd …
> Demo: ensure notification manager is created. 

- src/Ursa/Controls/Dialog/DialogControlBase.cs
1. Fixed the issue where specifying CanDragMoveProperty for components within the dialog in the user's code did not enable custom draggable area support.
2. Renamed title pointer event handlers for clarity, which represent handlers for all draggable areas besides the title.
---
The issue was introduced by #412 with commit dccb3c029c5d05423443dafdca5adb6cf6529430.
https://github.com/irihitech/Ursa.Avalonia/blob/5799646488116041bb857dd01222d419ae160281/src/Ursa/Controls/OverlayShared/OverlayDialogHost.Dialog.cs#L53-L96
Overrides for pointer events were removed for a refactor of title dragging, resulting in a failure of `CanDragMoveProperty`.
---
Fixes #643
> Fix CanDragMoveProperty for custom draggable area

- demo/Ursa.Demo/Views/MainWindow.axaml
- src/Ursa.Themes.Semi/Controls/IconButton.axaml
- src/Ursa.Themes.Semi/Controls/ScrollToButton.axaml
- src/Ursa.Themes.Semi/Controls/UrsaWindow.axaml
This pull request makes several changes to improve platform-specific property handling and simplifies styles in the `Ursa` project. The key updates include refactoring platform-specific property definitions for clarity and removing redundant styles for pressed states in buttons.
* Refactored `IsFullScreenButtonVisible` and `IsManagedResizerVisible` properties in `MainWindow.axaml` to use a more concise `OnPlatform` syntax with explicit `x:` namespace usage. (`demo/Ursa.Demo/Views/MainWindow.axaml`, [demo/Ursa.Demo/Views/MainWindow.axamlL18-R19](diffhunk://#diff-3a80804ae09127b0b5dffd5c27bb1aa3153275f8ae66b7c2a4a00a22b755e9daL18-R19))
* Simplified platform-specific definitions for `IsMinimizeButtonVisible`, `IsRestoreButtonVisible`, and `IsCloseButtonVisible` in `UrsaWindow.axaml` by …
> remove scale transform in Button &  simplify OnPlatform use case

- src/Ursa/Controls/Badge/Badge.cs
In the `Badge`, when the `Header` or `HeaderTemplate` changes, the `Bounds` value of `PART_BadgeContainer` is not updated before `UpdateBadgePosition` is called. Therefore, the Avalonia framework must be notified that changes to `HeaderProperty` and `HeaderTemplateProperty` should invalidate the arrange pass. This ensures that after `Bounds` is updated, `ArrangeOverride` is called again to recalculate the badge position.
---
* Change `Header`
https://github.com/user-attachments/assets/0390cbf3-ead6-44bc-8445-1b3636a7fca5
* Change `HeaderTemplate`
https://github.com/user-attachments/assets/97e23c96-daaf-4ef3-a349-b28b982cdf75
---
Fixes #661
> Fix Badge position miscalculation

- src/Ursa.Themes.Semi/Controls/Drawer.axaml
- src/Ursa.Themes.Semi/Controls/PathPicker.axaml
- src/Ursa.Themes.Semi/Converters/CornerRadiusTakeConverter.cs
- src/Ursa.Themes.Semi/Converters/ThicknessTakeConverter.cs
This pull request refactors the `Drawer.axaml` and `PathPicker.axaml` components to replace deprecated converters with updated ones and marks the old converters as obsolete. These changes improve maintainability by transitioning to the recommended `CornerRadiusMixerConverter` and `ThicknessMixerConverter`.
* In `src/Ursa.Themes.Semi/Controls/Drawer.axaml`, replaced all instances of `ThicknessTakeConverter` and `CornerRadiusTakeConverter` with `ThicknessMixerConverter` and `CornerRadiusMixerConverter`, respectively. This change affects multiple bindings for properties like `Margin`, `CornerRadius`, and `BorderThickness`. [[1]](diffhunk://#diff-ab71f24aedfaebc0ee8b32c3abe10be88ced64e49f6be3c41a84822ba8263ce4L23-R32) [[2]](diffhunk://#diff-ab71f24aedfaebc0ee8b32c3abe10be88ced64e49f6be3c41a848 …
> Replace outdated converters with new ones in Drawer and PathPicker

- .github/workflows/publish.yml
- .github/workflows/release-tag.yml
This pull request refactors and enhances the workflows for publishing and releasing builds across multiple platforms in `.github/workflows/publish.yml` and `.github/workflows/release-tag.yml`. Key changes include replacing platform-based inputs with specific architecture-based inputs, updating dependencies, and improving artifact handling.
* Refactored platform inputs (`platform`) to architecture-specific inputs (`win-x64`, `linux-x64`, `osx-arm64`, etc.) for better granularity in build configuration. [[1]](diffhunk://#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7L6-R166) [[2]](diffhunk://#diff-78ca2a162e43bc38ce9cf9eee54d1bfa9b15678fcc153cc554779bbb854b3a81L10-L140)
* Reorganized jobs to align with the new architecture-specific inputs, ensuring each job targets a …
> enhance Publish & Release workflow

- src/Ursa.Themes.Semi/Controls/TagInput.axaml
- src/Ursa/Controls/TagInput/ClosableTag.cs
This pull request updates the `ClosableTag` component in the `TagInput` control to improve its design and functionality. The key changes include replacing the `PathIcon` close button with a `Button`, updating styles for hover and pressed states, and simplifying the command handling logic.
* Added a design preview for the `ClosableTag` component in `TagInput.axaml` to enhance development and visualization. (`src/Ursa.Themes.Semi/Controls/TagInput.axaml`, [src/Ursa.Themes.Semi/Controls/TagInput.axamlR5-R7](diffhunk://#diff-7bf2b0913edfb47d9c1876cb791fa8a4d22fe01b330436a16f1fb3fc1dba2ac6R5-R7))
* Updated the `ClosableTag` template to replace the `PathIcon` close button with a styled `Button`, improving customization and usability. (`src/Ursa.Themes.Semi/Controls/TagInput.axaml`, …
> replace PathIcon with Button in ClosableTag

- src/Ursa/Controls/NavMenu/NavMenu.cs
- src/Ursa/Controls/NavMenu/NavMenuItem.cs
- src/Ursa/Controls/NavMenu/SelectionChangingEventArgs.cs
- tests/HeadlessTest.Ursa/Controls/NavMenuTests/CanSelectTests/Test.cs
- tests/HeadlessTest.Ursa/Controls/NavMenuTests/CanSelectTests/TestView1.axaml
- tests/HeadlessTest.Ursa/Controls/NavMenuTests/CanSelectTests/TestView1.axaml.cs
- tests/HeadlessTest.Ursa/Controls/NavMenuTests/CanSelectTests/TestView2.axaml
- tests/HeadlessTest.Ursa/Controls/NavMenuTests/CanSelectTests/TestView2.axaml.cs
In reality, `NavMenu` selection change means a heavy page toggle task. It is necessary to check whether the operation from UI is intended, and stop the change in advance. 
This pull request introduces a new `SelectionChanging` event in the `NavMenu` control, enabling finer control over selection changes. It also adds logic to handle scenarios where a selection change might be prevented. The changes include defining the event, implementing the supporting logic, and creating a new class for event arguments.
User can subscribe to `SelectionChanging` event, this event happens before real selection change starts. User can check the current state of your application. if you want to stop the selection change, you can set `e.CanSelect` to false, and the selection change won't happen.
Notice that …
> NavMenu: SelectionChanging Event

- src/Ursa.ReactiveUIExtension/Ursa.ReactiveUIExtension.csproj
- src/Ursa/Ursa.csproj
This PR addresses two issues:
1.  **Fix Ursa.ReactiveUIExtension dependency version issue:** Resolves problems related to the dependency version requirements for Ursa.ReactiveUIExtension.
2.  **Fix Ursa target framework recognition issue:** Corrects an issue where the target framework for Ursa could not be recognized in certain development environments.
> Fix Ursa.ReactiveUIExtension dependency version and project target framework recognition

- demo/Ursa.Demo/Pages/MultiComboBoxDemo.axaml
- src/Ursa.Themes.Semi/Controls/TagInput.axaml
- src/Ursa/Controls/ComboBox/MultiComboBox.cs
- src/Ursa/Controls/ComboBox/MultiComboBoxSelectedItemList.cs
- src/Ursa/Controls/TagInput/ClosableTag.cs
Currently, if you added `MultiComboBoxItem`s inside the axaml, for example:
```axaml
<u:MultiComboBox>
<u:MultiComboBoxItem>option 1</u:MultiComboBoxItem>
<u:MultiComboBoxItem>option 2</u:MultiComboBoxItem>
<u:MultiComboBoxItem>option 3</u:MultiComboBoxItem>
</u:MultiComboBox>
```
It didn't work properly; items were all considered to be the parent `DataContext`, which caused them to share their state and be displayed as the `ToString()` implementation of the parent's `DataContext`.
This small change seems to work properly and allow both type of usages, just like the regular `ComboBox`.
> Fix MultiComboBox to works with items added in axaml

- src/Ursa/Controls/Dialog/Options/OverlayDialogOptions.cs
- src/Ursa/Controls/Dialog/OverlayDialog.cs
- src/Ursa/Controls/NumPad/NumPad.cs
新增 OverlayDialogOptions.OnDialogControlClosed 委托属性， 支持自定义对话框关闭事件处理逻辑，并在 OverlayDialog 中
添加了相关事件绑定与解绑逻辑。
调整 NumPad 的显示与交互逻辑，确保在数字键盘关闭后，
目标输入控件能够重新获取焦点，优化用户体验。
> 增强 OverlayDialog 和 NumPad 的功能与交互体验
